#%% 
import random
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pickle
from ast import literal_eval
import math
import myokit
from scipy.signal import find_peaks # pip install scipy

#%% READ IN DATA

#%% GROUP BEST INIDIDUALS FOR ALL GENERATIONS

#%% CALCULATE EXACT RRC FOR BINARY GA

#%% SET THRESHOLD AND UPDATE LIST OF BEST INDIVIDUALS 

#%% ENSURE EACH INDIVIDUAL HAS A NORMAL AMOUNT OF BEAT-BEAT VARIABILITY (NO ALTERNANS)
 
#%% ELIMINATE ABNORMAL INDS FROM BEST LIST

#%% RUN CHALLENGES FOR ALL IN LIST OF BEST INDIVIDUALS 

#%% ELIMINATE INDS THAT WERENT IMMUNE TO ALL CHALLENGES

#%% ONCE FINAL GROUP IS CHOSEN, ASSESS DRUGS FROM PASSINI 2017 AND TOMEK 2019

#%% CORRELATION ANALYSIS

#%% NEW UPDATES TO GA

# %%
